import { Box, Container, Stack, Text } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import api from "./api/api";
import { HiLockClosed } from 'react-icons/hi';
import { BsDiscord, BsSteam } from 'react-icons/bs';
import { Skeleton, SkeletonCircle, SkeletonText } from '@chakra-ui/react'

export default function Home() {

  const [skins, setSkins] = useState([]);
  const [loading, setLoading] = useState([]);

  useEffect(() => {
    setLoading(true);

    const fetchData = async () => {
      setSkins(await api.skins.get());

      setTimeout(() => {
        setLoading(false);

      }, 2000);
    };
    fetchData();
  }, []);


  return (
    <>
      <Head>
        <title>Cajas por skins</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://community.cloudflare.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXU5A1PIYQNqhpOSV-fRPasw8rsUFJ5KBFZv668FFQxnaecIT8Wv9rilYTYkfTyNuiFwmhUvpZz3-2Z9oqg0Vew80NvZzuiJdeLMlhpwFO-XdA/330x192" />
      </Head>
      <main>

        <Container
          as="section"
          w="100%"
          maxW="container.xl"
          position="relative"
          display="flex"
          flexDirection="column"
        >

          <Box display='flex' justifyContent='center' mt='3rem' fontSize={{ sm: '4xl', md: '3xl', lg: '5xl' }} fontWeight="semibold">
            <Text
              as="h1"
              lineHeight="normal"
              fontWeight="bold"
              mt="-2"
              mr='0.5rem'
              fontSize={{ sm: '5xl', md: '5xl', lg: '6xl' }}
            >
              ¡Cambia tus
            </Text>
            <Text
              as="h1"
              fontWeight="800"
              lineHeight="normal"
              bgGradient="linear(to-r, red.500, red.600, red.500)"
              bgClip="text"
              mt="-2"
              mr='0.5rem'
              fontSize={{ sm: '5xl', md: '5xl', lg: '6xl' }}
            >
              Cajas
            </Text>
            <Text
              as="h1"
              lineHeight="normal"
              fontWeight="bold"
              mt="-2"
              mr='0.5rem'
              fontSize={{ sm: '5xl', md: '5xl', lg: '6xl' }}
            >
              por
            </Text>
            <Text
              as="h1"
              fontWeight="800"
              lineHeight="normal"
              bgGradient="linear(to-r, red.500, red.600, red.500)"
              bgClip="text"
              mt="-2"
              fontSize={{ sm: '5xl', md: '5xl', lg: '6xl' }}
            >
              Skins
            </Text>
            <Text
              as="h1"
              lineHeight="normal"
              fontWeight="bold"
              mt="-2"
              fontSize={{ sm: '5xl', md: '5xl', lg: '6xl' }}
            >
              !
            </Text>
          </Box>

          <Box
            as="section"
            textAlign="center"
            position="relative"
            w="100%"
            mb={'1rem'}
            mt={'2rem'}
          >
            <Box display='flex' flexDir='column' alignItems='center' gap={2}>
              <Box className="scale-image">
                <Image width={90} height={90} style={{ 'borderRadius': '50%' }} src='https://avatars.cloudflare.steamstatic.com/2bea4a86cf468c8721266e0c756afcba4073110e_full.jpg'></Image>
              </Box>

              <Box display='flex' flexDir='column' alignItems='center' gap='0.5rem'>
                <Text fontWeight="bold" w='100%' fontSize='xl' borderBottom='1px solid #d13535' pb={2}>FireWolf</Text>

                <Text color="grey" fontWeight="normal" fontSize='md'>Puedes contactarme mediante</Text>

                <Box display='flex' gap={3}>

                  <Box _hover={{ 'transform': 'scale(1.2)', 'msTransformOrigin': '50% 50%' }} transition='transform .4s'>
                    <Link title="Contáctame por Steam" href="https://steamcommunity.com/id/FireWolf__CSGO" rel="noopener noreferrer" target="_blank">
                      <BsSteam fontSize='1.5rem' />
                    </Link>
                  </Box>

                  <Box _hover={{ 'transform': 'scale(1.2)', 'msTransformOrigin': '50% 50%' }} transition='transform .4s'>
                    <Link title="Contáctame por Discord" href="https://steamcommunity.com/id/FireWolf__CSGO" rel="noopener noreferrer" target="_blank">
                      <BsDiscord fontSize='1.5rem' />
                    </Link>
                  </Box>

                </Box>
              </Box>
            </Box>
          </Box>

          <Box
            display="flex"
            flexDirection="column"
            width="100%"
          >

            <Text
              fontWeight="800"
              lineHeight="normal"
              bgGradient="linear(to-r, red.500, red.600, red.500)"
              bgClip="text"
              mr='0.5rem'
              fontSize={'3xl'}>Skins disponibles</Text>
            <Box display='flex' flexWrap='wrap' alignItems='center' mt='1rem' gap={5} bg='#23272e' p={4} borderRadius='9px'>

              {!loading && skins.map((skin) => (
                <Box className="skin-image-container" position='relative' w='13rem' key={skin.Nombre} display='flex' flexDir='column' alignItems='center' gap={2} bg='#1e2227' _hover={{ 'bg': '#3f3f45' }} cursor='pointer' py={3} px={1} borderRadius='9px'>
                  <Box h='5.5rem' mt='-0.5rem'>
                    <Image alt={skin.Nombre} width='120' height='120' style={{ 'borderRadius': '50%', 'objectFit': "cover" }} src={skin.ImagenURL}></Image>
                  </Box>

                  <Box position='absolute' top='0.5rem' right='0.4rem'>
                    {skin.Sticker1 && (
                      <Box title={skin.Sticker1Nombre}>
                        <Image alt={skin.Nombre + 'sticker 1'} width='28' height='28' style={{ 'objectFit': "cover" }} src={skin.Sticker1}></Image>
                      </Box>
                    )}
                  </Box>

                  <Box position='absolute' top='2rem' right='0.4rem'>
                    {skin.Sticker2 && (
                      <Box title={skin.Sticker2Nombre}>
                        <Image alt={skin.Nombre + 'sticker 2'} width='28' height='28' style={{ 'objectFit': "cover" }} src={skin.Sticker2}></Image>
                      </Box>
                    )}
                  </Box>

                  <Box position='absolute' top='3.5rem' right='0.4rem'>
                    {skin.Sticker3 && (
                      <Box title={skin.Sticker3Nombre}>
                        <Image alt={skin.Nombre + 'sticker 3'} width='28' height='28' style={{ 'objectFit': "cover" }} src={skin.Sticker3}></Image>
                      </Box>
                    )}
                  </Box>

                  <Box position='absolute' top='5rem' right='0.4rem'>
                    {skin.Sticker4 && (
                      <Box title={skin.Sticker4Nombre}>
                        <Image alt={skin.Nombre + 'sticker 4'} width='28' height='28' style={{ 'objectFit': "cover" }} src={skin.Sticker4}></Image>
                      </Box>
                    )}
                  </Box>

                  <Box w='100%' px={3} display='flex' flexDir='column'>
                    <Text fontWeight="semibold" fontSize='md' whiteSpace='nowrap' overflow='hidden' textOverflow='ellipsis' borderBottom='1px solid #d13535' pb={2}>{skin.Nombre} </Text>

                    <Box display='flex' justifyContent='space-between' w='100%' pt={1}>

                      <Box display='flex' flexDir='column' justifyContent='start'>
                        <Text color="grey" fontWeight="normal" fontSize='md'>{skin.Estado}</Text>
                        <Text color="grey" fontWeight="normal" fontSize='sm'>{skin.Float?.slice(0, 6)}</Text>
                      </Box>

                      <Box display='flex' alignItems='center' title="Este artículo tiene un bloqueo de intercambio por parte de Steam">
                        {skin.TradeLock == 'TRUE' && (
                          <HiLockClosed color="grey" style={{ 'marginRight': '-0.4rem' }} fontSize='1.4rem' />
                        )}
                      </Box>

                    </Box>
                  </Box>
                </Box>
              ))}

              {loading && (
                <Box minH='13rem' w='100%' display='flex' alignItems='center' flexWrap='wrap' gap={6}>
                  <Skeleton borderRadius='9px' height='12rem' w='13rem' />
                  <Skeleton borderRadius='9px' height='12rem' w='13rem' />
                  <Skeleton borderRadius='9px' height='12rem' w='13rem' />
                  <Skeleton borderRadius='9px' height='12rem' w='13rem' />
                  <Skeleton borderRadius='9px' height='12rem' w='13rem' />
                </Box>
              )}

            </Box>

          </Box>

        </Container>
      </main>
    </>
  )
}
